--- #YAML:1.0
name:                Catalyst-Plugin-DateTime-Constructor
version:             0.01
abstract:            DateTime plugin for Catalyst providinding some constructor.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - travail <travail@cabane.no-ip.org>
